import {Context, getDefaultContext} from './context';
import {computeTextAlternative} from './compute_text_alternative';

// Explicit roles allowing 'name from content'
// (https://www.w3.org/TR/wai-aria-1.1/#namefromcontent)
const NAME_FROM_CONTENT_ROLES = [
  'button',
  'cell',
  'checkbox',
  'columnheader',
  'gridcell',
  'heading',
  'link',
  'menuitem',
  'menuitemcheckbox',
  'menuitemradio',
  'option',
  'radio',
  'row',
  'rowgroup',
  'rowheader',
  'switch',
  'tab',
  'tooltip',
  'tree',
  'treeitem',
];

/**
 * HTML element types that allow name from content according
 * to their implicit aria roles.
 * (https://www.w3.org/TR/html-aria/#docconformance)
 */
const NAME_FROM_CONTENT_ELEM_NODE_NAME = [
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'tbody',
  'thead',
  'tfoot',
  'summary',
  'button',
];

/**
 * HTML input elements allow name from content when
 * they have the following values for 'type' attribute
 * (https://www.w3.org/TR/html-aria/#docconformance)
 */
const NAME_FROM_CONTENT_INPUT_TYPES = [
  'button',
  'checkbox',
  'image',
  'radio',
  'reset',
  'submit',
];

/**
 * Some HTML elements allow name from context only if certain
 * conditions apply. This function maps element types to functions that
 * determine if a specific element of that type allows name from content
 * (https://www.w3.org/TR/html-aria/#docconformance)
 * @param elemNodeName - the nodeName (tag type) of the element whose ability
 * to allow name from content is being calculated.
 * @return - a function that may be applied to an element of type elemNodeName
 * that returns true if that node allows name from content, and false otherwise.
 */
function getFunctionCalculatingAllowsNameFromContent(
  elemNodeName: string
): ((elem: HTMLElement) => boolean) | null {
  switch (elemNodeName) {
    case 'th':
      return (elem: HTMLElement) => {
        return elem.closest('table') !== null;
      };
    case 'td':
      return (elem: HTMLElement) => {
        return elem.closest('table') !== null;
      };
    case 'option':
      return (elem: HTMLElement) => {
        return elem.closest('select,datalist') !== null;
      };
    case 'input':
      return (elem: HTMLElement) => {
        const inputType = elem.getAttribute('type')?.trim().toLowerCase() ?? '';
        return NAME_FROM_CONTENT_INPUT_TYPES.includes(inputType);
      };
    case 'a':
      return (elem: HTMLElement) => {
        return elem.hasAttribute('href');
      };
    case 'area':
      return (elem: HTMLElement) => {
        return elem.hasAttribute('href');
      };
    case 'link':
      return (elem: HTMLElement) => {
        return elem.hasAttribute('href');
      };
    default:
      return null;
  }
}

/**
 * Calculates whether or not an element's name may be calculated using
 * its contents. Elements may allow name from content when they have certain
 * roles, be they explicit (role attribute) or implicit (semantic HTML).
 * @param elem - the function checks if 'elem' allows name from content
 * @return - true if elem allows name from content, false otherwise
 */
function allowsNameFromContent(elem: HTMLElement): boolean {
  const explicitRole = elem.getAttribute('role')?.trim().toLowerCase() ?? '';
  if (NAME_FROM_CONTENT_ROLES.includes(explicitRole)) {
    return true;
  }

  const elemNodeName = elem.nodeName.toLowerCase();
  if (NAME_FROM_CONTENT_ELEM_NODE_NAME.includes(elemNodeName)) {
    return true;
  }

  const nameFromContentFunction = getFunctionCalculatingAllowsNameFromContent(
    elemNodeName
  );
  if (nameFromContentFunction) {
    return nameFromContentFunction(elem);
  }

  return false;
}

export const TEST_ONLY = {allowsNameFromContent};

/**
 * Checks if 'elem' in with 'context' satisfies the conditions
 * necessary to apply rule 2F.
 * @param elem - elem whose text alternative is being computed
 * @param context - additional information about the context of elem
 * @return - whether or not rule 2Fs condition has been satisfied
 */
function rule2FCondition(elem: HTMLElement, context: Context): boolean {
  if (allowsNameFromContent(elem)) {
    return true;
  }

  if (context.directLabelReference) {
    return true;
  }

  if (context.inherited.partOfName) {
    return true;
  }

  return false;
}

/**
 * Gets text content generated by CSS pseudo elements for a given HTMLElement
 * @param elem - element whose css generated content is being calculated
 * @param pseudoElementName - the name of the pseudo element whose content is
 * being resolved.
 * @return - css generated content for pseudoElementName if such content exists,
 * empty string otherwise.
 */
function getCssContent(elem: HTMLElement, pseudoElementName: string): string {
  const cssContent: string = window.getComputedStyle(elem, pseudoElementName)
    .content;
  if (cssContent === 'none') {
    return '';
  } else {
    // slicing off unnecessary double quotes (")
    // from either end of the string.
    return cssContent.slice(1, -1);
  }
}

/**
 * Implementation of rule 2F
 * @param node - node whose text alternative is being calculated
 * @param context - additional info relevant to the calculation of nodes
 * text alternative
 * @return - text alternative for node if the conditions of 2F are satisfied,
 * null otherwise.
 */
export function rule2F(
  node: Node,
  context: Context = getDefaultContext()
): string | null {
  if (!(node instanceof HTMLElement)) {
    return null;
  }

  if (!rule2FCondition(node, context)) {
    return null;
  }

  const cssBeforeContent = getCssContent(node, ':before');
  const cssAfterContent = getCssContent(node, ':after');

  const textAlterantives: string[] = [];
  node.childNodes.forEach(childNode => {
    if (!context.inherited.visitedNodes.includes(childNode)) {
      context.inherited.visitedNodes.push(childNode);
      context.inherited.partOfName = true;

      const textAlterantive = computeTextAlternative(childNode, {
        inherited: context.inherited,
      });

      textAlterantives.push(textAlterantive);
    }
  });

  // Consider only non-empty text alternatives to prevent double
  // spacing between text alternatives in accumulatedText.
  // #SPEC_ASSUMPTION (F.1) : that accumulated texts should be space separated
  // for readability
  const accumulatedText = textAlterantives
    .filter(textAlterantive => textAlterantive !== '')
    .join(' ');

  // #SPEC_ASSUMPTION (F.2) : that CSS generated content should be
  // concatenated to accumulatedText
  return (cssBeforeContent + accumulatedText + cssAfterContent).trim();
}
